### ISSUE TITLE
Support for Group Submissions for Plagiarism Plugin

### ISSUE THREAD

**Issue by aspark21** [jmcgettrick/MoodleDirectV2#228] opened 2015-02-10 15:44 UTC
We would like to be able to use Group Submissions for other Moodle Tools through the Plagiarism Plugin, however the PP doesn't allow this.

**Comment by aspark21** [comment] 2015-02-10 15:55
For this, you have added support specifically for the Moodle Assignment, however this should be a feature available for all plugins in a standardised way rather than relying on handling special cases

Quote from the latest release's changelog:
"All students in a group submission to a Moodle assignments can now see the similarity score."

Other students in a group would not currently be able to review their submission.

**Comment by amclarty** [comment] 2015-02-10 16:00
@aspark21, do you mean you would like to use the PP with other Moodle activities?

**Comment by aspark21** [comment] 2015-02-10 16:03
Yes, though the PP already works with other 3rd party Moodle Plugins, but this functionality isn't available to them.

**Comment by mhughes2k** [comment] 2015-02-10 16:11
The problem is more the Plagiarism API, it's not really clearly defined about what it's meant to do, and what data it gets passed in.

You get a chunk of data and the plagiarism plugin needs to work out what all of the information pertains to as it could be *anything*.

**Comment by jmcgettrick** [comment] 2015-08-12 14:01
This is being closed as we currently support group submissions to the best of our ability. We can only show a user the originality score, as only the student who owns the submission or an instructor are allowed to view the report in Turnitin.

**Closed by jmcgettrick** 2015-08-12 14:01 UTC
